### ISSUE TITLE
Problem with SSL Cert?

### ISSUE THREAD

**Issue by chrisndeca** [jonasehrlich/ek-scraper#3]
Getting the following error when trying to run ek-scraper

ek-scraper: error: Cannot connect to host www.ebay-kleinanzeigen.de:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]

This error occurred while using the sample URL in the config.json file, and when using a different search.

**Comment by jonasehrlich** [comment]
Which Python version, OS (version) and version of aiohttp are you using? 
Haven't looked into this in a long time, but I did not see any issues when running it on MacOS in a fresh 3.11.1 virtualenv.

**Comment by chrisndeca** [comment]
Python 3.11.1
Mac OS 12.6
aiohttp 3.8.3

**Comment by chrisndeca** [comment]
FWIW, I upgraded to 0.0.5 and am still seeing the issue.

**Comment by jonasehrlich** [comment]
Updating to 0.0.5 would not fix this issue. How did you install Python? Did you use the Package from python.org?

In case you used that you might have missed the step to install the certificates. To install the certificates, navigate to `/Applications/Python 3.11` and run `Install Certificates.command`.

If you installed Python through Homebrew or pyenv this step should not be necessary.
