### ISSUE TITLE
Exclude patterns funktionieren nicht?

### ISSUE THREAD

**Issue by clemuu** [jonasehrlich/ek-scraper#66]
Hi, wenn ich in meiner Config die Exclude-Patterns nutzen will kommt leider eine Fehlermeldung. Vielleicht mache ich etwas falsch, aber habe es mit normalen Worten oder auch Regex Ausdrücken versucht.

`clem@MacBook-Air ek-scraper % ek-scraper run --temp-data-store /Users/clem/Downloads/ek-scraper/configuration.json
1 validation error for Config
filter.exclude_patterns
  Value error, cannot process flags argument with a compiled pattern [type=value_error, input_value=['test'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.6/v/value_error%`

Der part der Config dazu:

`    "filter": {
        "exclude_topads": true,
        "exclude_patterns": [
            "test"
        ]
    },`

**Comment by jonasehrlich** [comment]
Should be fixed in https://github.com/jonasehrlich/ek-scraper/commit/2bbbeb15f0ccc915225b1e08d9ebd0cd52cfbdd4.

I tagged a new version v0.2.3 which is already published to PyPI.
